# Generated by Django 5.2.12 on 2026-04-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo_profil',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to='profils/%Y/%m/', verbose_name='photo de profil'),
        ),
        migrations.AddField(
            model_name='user',
            name='troisieme_nom',
            field=models.CharField(blank=True, max_length=150, verbose_name='troisième nom'),
        ),
    ]
