# Generated by Django 5.2.12 on 2026-04-01 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=128, unique=True, verbose_name='nom')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('students_can_manage', models.BooleanField(default=False, help_text='Si activé, un étudiant auteur peut créer / modifier / supprimer ses publications dans cette catégorie (ex. recherches scientifiques).', verbose_name='étudiants peuvent gérer leurs publications')),
            ],
            options={
                'verbose_name': 'catégorie de publication',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='titre')),
                ('contenu', models.TextField(verbose_name='contenu')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('archive', 'Archivé')], db_index=True, default='actif', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'publication',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=255, verbose_name='intitulé')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('lieu', models.CharField(blank=True, max_length=255, verbose_name='lieu')),
                ('date_debut', models.DateField(verbose_name='date de début')),
                ('date_fin', models.DateField(verbose_name='date de fin')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('expire', 'Expiré')], db_index=True, default='actif', max_length=20)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to='inscription.filiere')),
            ],
            options={
                'verbose_name': 'horaire',
                'ordering': ['date_debut', 'filiere'],
            },
        ),
    ]
