# Generated by Django 5.2.12 on 2026-04-01 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publication',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='post.categoriepost'),
        ),
        migrations.AddIndex(
            model_name='horaire',
            index=models.Index(fields=['filiere', 'date_debut', 'date_fin'], name='post_horair_filiere_396ba8_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['-created_at', 'statut'], name='post_public_created_3592db_idx'),
        ),
    ]
