# Generated by Django 5.2.12 on 2026-04-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horaire',
            name='intitule',
        ),
        migrations.RemoveField(
            model_name='horaire',
            name='lieu',
        ),
        migrations.AddField(
            model_name='horaire',
            name='fichier',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to='horaires/%Y/%m/', verbose_name='fichier horaire (PDF ou image)'),
        ),
    ]
