# Generated by Django 5.2.12 on 2026-04-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_horaire_fichier_sans_intitule_lieu'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='type_pub',
            field=models.CharField(choices=[('communication', 'Communication'), ('actualite', 'Actualité')], db_index=True, default='actualite', max_length=20, verbose_name='type de publication'),
        ),
    ]
