# Generated by Django 5.2.12 on 2026-04-02 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_publication_type_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='image',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to='publications/%Y/%m/', verbose_name='image'),
        ),
    ]
