# Generated by Django 5.2.12 on 2026-04-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AffectFiliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='date de fin')),
            ],
            options={
                'verbose_name': 'affectation filière',
                'verbose_name_plural': 'affectations filière',
            },
        ),
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=191, verbose_name='nom')),
                ('code', models.CharField(blank=True, max_length=32, verbose_name='code')),
            ],
            options={
                'verbose_name': 'domaine',
                'ordering': ['institution', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=191, verbose_name='nom')),
                ('code', models.CharField(blank=True, max_length=32, verbose_name='code')),
            ],
            options={
                'verbose_name': 'filière',
                'verbose_name_plural': 'filières',
                'ordering': ['domaine', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=191, unique=True, verbose_name='nom')),
                ('code', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='code')),
                ('adresse', models.TextField(blank=True, verbose_name='adresse')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'institution',
                'ordering': ['nom'],
            },
        ),
    ]
