# Generated by Django 5.2.12 on 2026-04-01 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscription', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='affectfiliere',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_filiere', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filiere',
            name='domaine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='inscription.domaine'),
        ),
        migrations.AddField(
            model_name='affectfiliere',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='inscription.filiere'),
        ),
        migrations.AddField(
            model_name='domaine',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domaines', to='inscription.institution'),
        ),
        migrations.AddConstraint(
            model_name='filiere',
            constraint=models.UniqueConstraint(fields=('domaine', 'nom'), name='uniq_inscription_filiere_domaine_nom'),
        ),
        migrations.AddConstraint(
            model_name='affectfiliere',
            constraint=models.UniqueConstraint(fields=('user', 'filiere'), name='uniq_affect_user_filiere'),
        ),
        migrations.AddConstraint(
            model_name='domaine',
            constraint=models.UniqueConstraint(fields=('institution', 'nom'), name='uniq_inscription_domaine_institution_nom'),
        ),
    ]
